# The default maximum distance from the robot at which an obstacle will be inserted into the cost map in meters.
# This can be over-ridden on a per-sensor basis. (double, default: 2.5)
obstacle_range: 3.0
# The default range in meters at which to raytrace out obstacles from the map using sensor data.
# This can be over-ridden on a per-sensor basis. (double, default: 3.0)
raytrace_range: 3.5

# The maximum height of any obstacle to be inserted into the costmap in meters.
# This parameter should be set to be slightly higher than the height of your robot. (double, default: 2.0)
max_obstacle_height: 0.25

footprint:
  - [0.0800, 0]
  - [0.0703, -0.0406]
  - [0.0423, -0.0732]
  - [0.0250, -0.0829]
  - [0.0250, -0.1250]
  - [-0.0250, -0.1250]
  - [-0.0250, -0.0887]
  - [-0.0437, -0.0819]
  - [-0.0817, -0.0468]
  - [-0.1000, 0]
  - [-0.0817, 0.0468]
  - [-0.0437, 0.0819]
  - [-0.0250, 0.0887]
  - [-0.0250, 0.1250]
  - [0.0250, 0.1250]
  - [0.0250, 0.0829]
  - [0.0423, 0.0732]
  - [0.0703, 0.0406]

# http://wiki.ros.org/costmap_2d/hydro/inflation
# The radius in meters to which the map inflates obstacle cost values. (double, default: 0.55)
inflation_radius: 0.5

# A scaling factor to apply to cost values during inflation.
# The cost function is computed as follows for all cells in the costmap further than the inscribed
# radius distance and closer than the inflation radius distance away from an actual obstacle:
# exp(-1.0 * cost_scaling_factor * (distance_from_obstacle - inscribed_radius)) * (costmap_2d::INSCRIBED_INFLATED_OBSTACLE - 1),
# where costmap_2d::INSCRIBED_INFLATED_OBSTACLE is currently 254.
cost_scaling_factor: 3.0

map_type: costmap
observation_sources: scan
scan:
  {
    sensor_frame: base_scan,
    data_type: LaserScan,
    topic: scan,
    marking: true,
    clearing: true,
  }
