local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint
  
  # The frequency in Hz for the map to be updated. (double, default: 5.0) 
  update_frequency: 10.0
  # The frequency in Hz for the map to be publish display information. (double, default: 0.0) 
  publish_frequency: 10.0

  # Specifies the delay in transform (tf) data that is tolerable in seconds.
  # This parameter serves as a safeguard to losing a link in the tf tree while still
  # allowing an amount of latency the user is comfortable with to exist in the system.
  # For example, a transform being 0.2 seconds out-of-date may be tolerable, but a transform
  # being 8 seconds out of date is not. If the tf transform between the coordinate frames
  # specified by the global_frame and robot_base_frame parameters is transform_tolerance
  # seconds older than ros::Time::now(), then the navigation stack will stop the robot. 
  transform_tolerance: 0.5  

  static_map: false

  # Whether or not to use a rolling window version of the costmap. 
  # If the static_map parameter is set to true, this parameter must be set to false.  
  rolling_window: true

  # The width of the map in meters. (int, default: 10) 
  width: 3
  
  # The height of the map in meters. (int, default: 10) 
  height: 3

  # The resolution of the map in meters/cell. 
  resolution: 0.01