map_update_interval: 2.0
maxUrange: 5.0

linearUpdate: 0.2
angularUpdate: 0.2
temporalUpdate: 0.5 # Process a scan if the last scan processed is older than the update time in seconds. A value less than zero will turn time based updates off. 
resampleThreshold: 0.5

particles: 100 # Number of particles in the filter (int, default: 30)
minimumScore: 50

xmax: 10.0
xmin: -10.0
ymax: 10.0
ymin: -10.0

delta: 0.02 # Resolution of the map (in metres per occupancy grid block) 

# Keep default
sigma: 0.05 # The sigma used by the greedy endpoint matching (float, default: 0.05) 
kernelSize: 1 # The kernel in which to look for a correspondence (int, default: 1) 
lstep: 0.05 # The optimization step in translation (float, default: 0.05) 
astep: 0.05 # The optimization step in rotation 
iterations: 5 # The number of iterations of the scanmatcher 

lsigma: 0.075 # The sigma of a beam used for likelihood computation float, default: 0.075) 
ogain: 3.0 # Gain to be used while evaluating the likelihood, for smoothing the resampling effects float, default: 3.0)
lskip: 0 # Number of beams to skip in each scan. Take only every (n+1)th laser ray for computing a match (0 = take all rays) 

srr: 0.1 # Odometry error in translation as a function of translation (rho/rho) (float, default: 0.1) 
srt: 0.2 # Odometry error in translation as a function of rotation (rho/theta) (float, default: 0.2) 
str: 0.1 # Odometry error in rotation as a function of translation (theta/rho) (float, default: 0.1) 
stt: 0.2 # Odometry error in rotation as a function of rotation (theta/theta) (float, default: 0.2) 

llsamplerange: 0.01 # Translational sampling range for the likelihood  (float, default: 0.01) 
llsamplestep: 0.01 # Translational sampling step for the likelihood (float, default: 0.01) 
lasamplerange: 0.005 # Angular sampling range for the likelihood (float, default: 0.005) 
lasamplestep: 0.005 # Angular sampling step for the likelihood (float, default: 0.005) 